KS-11-5 forum messages
miroks404/KotlinSpring pull request #58
Opened 2024-10-19 01:09 UTC by miroks404

2024-10-19 12:55 UTC, ievetrovdev requested changes

2024-10-19 12:55 UTC, ievetrovdev commented on src/main/kotlin/lesson11/lesson11_task5.kt
> +        return newMessage
а зачем возвращать создаваемые объект если ты его дозволяешь в списке внутри класса?

2024-10-19 12:55 UTC, ievetrovdev commented on src/main/kotlin/lesson11/lesson11_task5.kt
> +//Использовал gpt, потому что у меня выводилсоь по одному последнему сообщению юзера(
Не стоит копировать вариант из gpt? максимум гуглить непонятные моменты, а не полные решения

2024-10-19 12:55 UTC, ievetrovdev commented on src/main/kotlin/lesson11/lesson11_task5.kt
> +        listOfMembers[newUser.userId] = newUser.userName
тут тоже как то не логично, создаешь объект, но не записываешь его

2024-10-19 12:55 UTC, ievetrovdev commented on src/main/kotlin/lesson11/lesson11_task5.kt
> +    val listOfMembers: MutableMap<String, String> = mutableMapOf(),
а почему тут мапа, а не список ForumMember?

2024-10-19 13:07 UTC, miroks404 commented on src/main/kotlin/lesson11/lesson11_task5.kt
> +//Использовал gpt, потому что у меня выводилсоь по одному последнему сообщению юзера(
я как раз и спросил у него непонятный момент, то что я сам сделал, но выводилось только послденее сообщение, тоесть в список только последние значения записывались

2024-10-20 10:23 UTC, ievetrovdev approved these changes

2024-10-20 15:02 UTC, merged