KS-15-1 interface beings
miroks404/KotlinSpring pull request #74
Opened 2024-10-27 11:25 UTC by miroks404

2024-10-27 18:27 UTC, ievetrovdev requested changes

2024-10-27 18:27 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task1.kt
> +abstract class Beings : FlyMovingMethod, SwimMovingMethod {
Нарушается принцип единой ответственности (см. [SOLID](https://habr.com/ru/companies/productivity_inside/articles/505430/)) потому что теперь я по ошибке или случайно могу заставить карася полететь и все сломается

2024-10-27 18:27 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task1.kt
> +) : Beings() {
Здесь у тебя некорректно используется интерфейс, каждый класс должен реализовывать интерфейсы которые ему нужны. Интерфейс — он по сути безымянный, то есть универсальный. Например, он может отвечать только за плавание или только за полет (любого существа).

2024-10-27 18:27 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task1.kt
> +        TODO("Not yet implemented")
TODO оставляется чтобы реализовать какой-то функционал, то есть сейчас я могу заставить карася летать

2024-10-28 16:36 UTC, ievetrovdev requested changes

2024-10-28 16:36 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task1.kt
> +) : Beings(), SwimMovingMethod {
Окей, а как быть с тем, что, например, утка может и плавать, и летать?

2024-10-28 19:40 UTC, miroks404 commented on src/main/kotlin/lesson15/lesson15_task1.kt
> +) : Beings(), SwimMovingMethod {
блин, хаха, забыл что она летать может

2024-10-29 17:47 UTC, ievetrovdev approved these changes

2024-10-29 18:27 UTC, merged